### PR TITLE
Add email validation when form submitted.

### PR DESCRIPTION
**Pull request by Kangarooss**

### CODE REVIEW

**Comment by wy8881** [comment]
Already have this

**Comment by Kangarooss** [comment]
By default, log in page can accept an email address like "a@d" that is invalid.
This update can improve robust of the system.

**Comment by Kangarooss** [comment]
> Already have this
By default, log in page can accept an email address like "a@d" that is invalid.
This update can improve robust of the system.
This validation is used before submission.

**Comment by wy8881** [comment]
I fix this few hours ago

**Pull request closed without merging**
